version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: expressBMI
    restart: always
    build: .
    ports:
      - '80:3000'

    external_links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongoBMI
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'

volumes:
 mongodb:
