version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-node-express
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo1
    ports:
      - '27017:27017'

