version: '3'
services:
  gcc:
    build: 
      context: "./multistage"
  mongo-express:
    image: mongo-express
    container_name: expressBMI
    restart: always
    build: .
    ports:
      - '80:3000'

    external_links:
      - mongo
  app:
    image: nginx
    container_name: rev-proxy
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - '81:81'
      - '443:443'
  mongo:
    image: mongo
    container_name: mongoBMI
    volumes:
      - mongoBMI:/data/db
    ports:
      - '27017:27017'

volumes:
 mongoBMI:
