version: '3'
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-node-express
    restart: always
    build: .
    ports:
      - '80:3000'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    external_links:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongo1
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
